### ISSUE TITLE
testnet-runtime-v0.4.2

### ISSUE THREAD

**Issue by al3mart** [r0gue-io/pop-node#372]
## Release Readiness Tracking

> _Runtime Release_

- [x] All changes have passed peer-review. Reviews on going in #369
- [x] Update runtime crate version. Note that `pop-runtime-devnet` is usually not updated. Done in #369 
- [x] Runtime spec version is updated.
- [x] If needed, new benchmarks have been run. A diff between the new weights and the current ones has been reviewed.
    - [`substrate-weight-compare`](https://github.com/ggwpez/substrate-weight-compare) can be used for this purpose.
     - Weights have been compared using `substrate-weight-compare`, the only diff being the newly included pop api fungibles weights.
- [x] Execution of [`try-runtime`](https://github.com/paritytech/try-runtime-cli) doesn't point out any missing migrations or other items requiring action. Done as part of #369 - [logs](https://gist.github.com/al3mart/a707c9c58893bcf3e04d21564f01f4af).

## Testing Tracking

- [x] Local upgrade test runs as expected.

1. Build the latest release.
2. Launch a network using `pop up parachiain -f networks/testnet.toml -v`.
    - `pop-node` version can be verified via: `rpc calls -> system -> version()`
    - Runtime version can be verified via: `rpc calls -> state -> getRuntimeVersion()`

> _Runtime release_

_The new runtime might need a certian `pop-node` version to be deployed first, if that is the case make sure you follow the above steps for a Node Release_

3. Do a runtime upgrade using the new runtime release -- can be found in `./target/release/wbuild/pop-runtime-testnet/pop_runtime_testnet.compact.compressed.wasm`.
4. Verify the runtime upgrade was successful:
    - The runtime version should have changed.
    - The corresponding migrations should have run.
    - Pop Network is still producing blocks.
    
    
![image](https://github.com/user-attachments/assets/aed04368-0328-447b-bd31-f41785323d0e)
![image](https://github.com/user-attachments/assets/3a603000-1f4a-4f7b-85ef-d5d96e7cd744)

`state.getRuntimeVersion`:
```bash
{
  specName: pop
  implName: pop
  authoringVersion: 1
  specVersion: 402
  implVersion: 0
  apis: [
    [
      0xdd718d5cc53262d4
      1
    ]
    [
      0xdf6acb689907609b
      5
    ]
    [
      0x37e397fc7c91f5e4
      2
    ]
    [
      0x40fe3ad401f8959a
      6
    ]
    [
      0xd2bc9897eed08f15
      3
    ]
    [
      0xf78b278be53f454c
      2
    ]
    [
      0xab3c0572291feb8b
      1
    ]
    [
      0xbc9d89904f5b923f
      1
    ]
    [
      0x37c8bb1350a9a2a8
      4
    ]
    [
      0xf3ff14d5ab527059
      3
    ]
    [
      0x68b66ba122c93fa7
      2
    ]
    [
      0xd7bdd8a272ca0d65
      1
    ]
    [
      0xea93e3f16f3d6962
      2
    ]
    [
      0x899a250cbe84f250
      1
    ]
    [
      0xfbc577b9d747efd6
      1
    ]
  ]
  transactionVersion: 1
  stateVersion: 1
}
```

- [x] Successful execution of `try-runtime` .
```
cargo build --release --features=try-runtime -p <runtime-crate>
try-runtime --runtime ./target/release/wbuild/pop-runtime-testnet/pop_runtime_testnet.compact.compressed.wasm on-runtime-upgrade live --uri wss://rpc3.paseo.popnetwork.xyz:443
```

- [x] (Advised) Runtime upgrade on a local **fork** of Pop Network.

_More instructions around using chopsticks for this can be found in [.chopsticks directory](../../.chopsticks)_

1. Launch the local fork:
```shell
    npx @acala-network/chopsticks@latest xcm -r ./.chopsticks/paseo.yml -p ./.chopsticks/testnet.yml
```
2. Do a runtime upgrade using the new runtime release -- can be found in `./target/release/wbuild/pop-runtime-testnet/pop_runtime_testnet.compact.compressed.wasm`.
3. Might be needed to trigger block production on Pop Network:
```shell
    websocat ws://localhost:8000
    {"jsonrpc":"2.0","id":2,"method":"dev_newBlock","params":[{"count":20}]}
```

![image](https://github.com/user-attachments/assets/1f0be16f-5c21-454d-8aef-d089388087e2)
`state.getRuntimeVersion`:
```
{
  specName: pop
  implName: pop
  authoringVersion: 1
  specVersion: 402
  implVersion: 0
  apis: [
    [
      0xdd718d5cc53262d4
      1
    ]
    [
      0xdf6acb689907609b
      5
    ]
    [
      0x37e397fc7c91f5e4
      2
    ]
    [
      0x40fe3ad401f8959a
      6
    ]
    [
      0xd2bc9897eed08f15
      3
    ]
    [
      0xf78b278be53f454c
      2
    ]
    [
      0xab3c0572291feb8b
      1
    ]
    [
      0xbc9d89904f5b923f
      1
    ]
    [
      0x37c8bb1350a9a2a8
      4
    ]
    [
      0xf3ff14d5ab527059
      3
    ]
    [
      0x68b66ba122c93fa7
      2
    ]
    [
      0xd7bdd8a272ca0d65
      1
    ]
    [
      0xea93e3f16f3d6962
      2
    ]
    [
      0x899a250cbe84f250
      1
    ]
    [
      0xfbc577b9d747efd6
      1
    ]
  ]
  transactionVersion: 1
  stateVersion: 1
}
```
Nothing outstanding regarding block production.

## Release

> _Runtime release_

To happen after #369 is merged:

- [x] New runtime release has been created: https://github.com/r0gue-io/pop-node/releases/tag/testnet-v0.4.2
    - [x] Tag created `testnet-v0.4.2`.
    - [x] Point to the previous runtime release to create a proper diff.
    - [x] Provide a description and then release notes.

- [x] Create the authorization call data
    - `0x0f000009c4153e3aaf9a27f4544a86fddb07fa3ada964a9ea583c09fe7d783d5d3f2446a`
    - https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc1.paseo.popnetwork.xyz#/extrinsics/decode/0x0f000009c4153e3aaf9a27f4544a86fddb07fa3ada964a9ea583c09fe7d783d5d3f2446a

**Comment by al3mart** [comment]
Runtime has been enacted on chain
